services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: guardlab
      POSTGRES_USER: guardlab_bootstrap
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env} #Берем из .env
      DB_OWNER_PASSWORD: ${DB_OWNER_PASSWORD:?Set DB_OWNER_PASSWORD in .env}
      PLATFORM_DB_PASSWORD: ${PLATFORM_DB_PASSWORD:?Set PLATFORM_DB_PASSWORD in .env}
      SANDBOX_DB_PASSWORD: ${SANDBOX_DB_PASSWORD:?Set SANDBOX_DB_PASSWORD in .env}
    volumes:
      - postgres_data:/var/lib/postgresql/data #храним данные даже после остановки контейнера
      - ./infra/postgres/init-roles.sql:/docker-entrypoint-initdb.d/01-init-roles.sql:ro #автоматически выполняем скрипт при запуске контейнера если это первый запуск
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guardlab_bootstrap -d guardlab"]
      interval: 5s
      timeout: 3s
      retries: 10

  db-init:
    build:
      context: .
      dockerfile: src/GuardLab.DbMigrator/Dockerfile
    environment:
      ConnectionStrings__Platform: "Host=postgres;Port=5432;Database=guardlab;Username=db_owner;Password=${DB_OWNER_PASSWORD:?Set DB_OWNER_PASSWORD in .env}"
      ConnectionStrings__Sandbox: "Host=postgres;Port=5432;Database=guardlab;Username=db_owner;Password=${DB_OWNER_PASSWORD:?Set DB_OWNER_PASSWORD in .env}"
      Admin__Email: ${ADMIN_EMAIL:?Set ADMIN_EMAIL in .env}
      Admin__Password: ${ADMIN_PASSWORD:?Set ADMIN_PASSWORD in .env}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: .
      dockerfile: src/GuardLab.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Platform: "Host=postgres;Port=5432;Database=guardlab;Username=platform_app;Password=${PLATFORM_DB_PASSWORD:?Set PLATFORM_DB_PASSWORD in .env}"
      ConnectionStrings__Sandbox: "Host=postgres;Port=5432;Database=guardlab;Username=lab_app;Password=${SANDBOX_DB_PASSWORD:?Set SANDBOX_DB_PASSWORD in .env}"
      Jwt__SigningKey: ${JWT_SIGNING_KEY:?Set JWT_SIGNING_KEY in .env}
      Jwt__Issuer: ${JWT_ISSUER:-GuardLab}
      Jwt__Audience: ${JWT_AUDIENCE:-GuardLab.Api}
    depends_on:
      db-init:
        condition: service_completed_successfully

  web:
    build:
      context: .
      dockerfile: src/GuardLab.Web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  postgres_data:
