apiVersion: v1
kind: Secret
metadata:
  name: guardlab-secrets
  namespace: guardlab
stringData:
  POSTGRES_PASSWORD: "замени на свое"
  DB_OWNER_PASSWORD: "GuardLabOwner2026"
  PLATFORM_DB_PASSWORD: "GuardLabOwner2026"
  SANDBOX_DB_PASSWORD: "GuardLabOwner2026"
  JWT_SIGNING_KEY: "Gv4XbTHBrz7x8wT-Y0SZAkzfsbpF0bslEbbMq9tivgg"
  JWT_ISSUER: "GuardLab"
  JWT_AUDIENCE: "GuardLab.Api"
  ADMIN_EMAIL: "admin@example.local"
  ADMIN_PASSWORD: "admin"
