apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: guardlab
spec:
  type: ClusterIP # только внутри кластера
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
